# Generated by Django 6.1.1 on 2026-10-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('document_type', models.CharField(choices=[('company', 'Company'), ('brochure', 'Brochure'), ('capability', 'Capability Statement'), ('certificate', 'Certificate'), ('policy', 'Policy'), ('other', 'Other')], default='company', max_length=30)),
                ('file', models.FileField(upload_to='downloads/')),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Download Document',
                'verbose_name_plural': 'Download Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
