# Generated by Django 6.1.1 on 2026-10-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='points',
            field=models.JSONField(blank=True, default=list, help_text='Enter key service areas as a JSON list.'),
        ),
    ]
