# Generated by Django 6.1.2 on 2026-10-07 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industries', '0001_initial'),
    ]

    operations = [
    ]
